### ISSUE TITLE
stack-safe foldM

### ISSUE THREAD

**Issue by jamesdbrock** [jamesdbrock/purescript-arraybuffer-builder#7]
Add a `MonadRec` constraint to `foldM`, like

https://pursuit.purescript.org/packages/purescript-arrays/6.0.1/docs/Data.Array#v:foldRecM

**Comment by jamesdbrock** [comment]
And implement it in terms of https://pursuit.purescript.org/packages/purescript-tailrec/5.0.1/docs/Control.Monad.Rec.Class#v:tailRecM for stack-safety.

Then implement `foldl` in terms of `foldM`.

https://github.com/jamesdbrock/purescript-arraybuffer-builder/blob/e2b73e0327e5eb49e0b320bd5a73d19deb2c52db/src/Data/ArrayBuffer/Internal.purs#L206-L209

**Comment by jamesdbrock** [comment]
https://pursuit.purescript.org/packages/purescript-free/6.0.1/docs/Control.Comonad.Cofree

**Comment by considerate** [comment]
@jamesdbrock How is the cofree comonad relevant here? I think foldM more closely corresponds to the free monad (or maybe even just the free applicative) rather than the cofree comonad.

**Comment by jamesdbrock** [comment]
> @jamesdbrock How is the cofree comonad relevant here? I think foldM more closely corresponds to the free monad (or maybe even just the free applicative) rather than the cofree comonad.

Aside: @considerate is going to explain to me how I can replace this stack-unsafe `Builder` implementation with a stack-safe `Free` monad.

**Comment by considerate** [comment]
This might work:

```Haskell

data Builder x
  = Node x String x
  | Null
  deriving (Functor)

foldM :: forall m a. Monad m => (forall r. String -> a -> m a) -> Free1 Monad Builder a -> a -> m a
foldM f builder a0 = let ReaderT g = runFreeM (\b -> ReaderT $ \a -> folding f b a) builder in g a0

folding :: Monad m => (String -> a -> m a) -> Builder (Free1 Monad Builder a) -> a -> m (Free1 Monad Builder a)
folding f (Node l s r) a =
  foldM f l a >>= \a' ->
    f s a' >>= \a'' ->
      pure <$> foldM f r a''
folding _ Null a = pure (pure a)
```

**Comment by jamesdbrock** [comment]
https://github.com/justinwoo/purescript-arraybuffer-builder/blob/fold-js/src/Data/ArrayBuffer/Internal.js
